name: aksara_ebook_apps
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  intl: any
  auto_route: ^8.0.3
  google_fonts: ^6.2.1
  sizer: ^2.0.15
  loader_overlay: ^4.0.0
  flutter_spinkit: ^5.2.1
  fluttersax: ^0.0.6
  flutter_localizations:
    sdk: flutter
  iconsax: ^0.0.8
  percent_indicator: ^4.2.3
  sqflite: any
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  auto_route_generator: ^8.0.0

flutter:
  generate: true
  assets:
    - lib/assets/book_cover_1.png
    - lib/assets/book_cover_2.png
    - lib/assets/book_cover_3.png
    - lib/assets/book_cover_4.png
    - lib/assets/profile_pict.jpg
    - lib/assets/onboarding_1.png
    - lib/assets/onboarding_2.png
    - lib/assets/onboarding_3.png
    - lib/assets/aksara_logo.png
    - lib/assets/aksara_logo.jpg
  uses-material-design: true